name: Build and deploy Node.js app to Azure Web App - smart-travel-echo-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: samples/javascript_nodejs/02.echo-bot
        run: npm install

      - name: Build (if needed)
        working-directory: samples/javascript_nodejs/02.echo-bot
        run: npm run build --if-present

      - name: Skip tests (no test script)
        run: echo "Skipping tests — none defined yet."

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E94452538EF94688832DC3BE30CEEA9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_819B7FC77E0842E49B7EAB6F12E6B7F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB9409A079E0410B9D8B4C75E39EF404 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'smart-travel-echo-bot'
          slot-name: 'Production'
          package: samples/javascript_nodejs/02.echo-bot
